apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: dixre/click-notification-service
          env:
            - name: NODE_ENV
              value: development
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: clickacademic
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: TWILLIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twillio-secrets
                  key: TWILLIO_AUTH_TOKEN
            - name: TWILLIO_SSID
              valueFrom:
                secretKeyRef:
                  name: twillio-secrets
                  key: TWILLIO_SSID
            - name: TWILLIO_SENDER_PHONENUMBER
              valueFrom:
                secretKeyRef:
                  name: twillio-secrets
                  key: TWILLIO_SENDER_PHONENUMBER
            - name: MAIL_TRAP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mailtrap-secrets
                  key: MAIL_TRAP_TOKEN
            - name: SENDER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: mailtrap-secrets
                  key: SENDER_ADDRESS
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-srv
spec:
  selector:
    app: notification-service
  ports:
    - name: notification-service
      protocol: TCP
      port: 3000
      targetPort: 3000
