name: test:anonymous-frontend
on:
  pull_request:
    branches:
      - master
    paths:
      - "frontends/Admin-Anonymous/**"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v2
      - run: npm ci && npm run build --workspaces
      - run: cd frontends/Admin-Anonymous && npm install && npm run test:ci
